# https://packaging.python.org/ja/latest/guides/writing-pyproject-toml/
[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "lammps-utils"
dynamic = ["version"]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "rdkit",
    "networkx",
    "joblib",
    "py3Dmol",
    "moltemplate",
]
requires-python = ">= 3.9,<3.14" # because of packmol
authors = [{ name = "yu9824" }]
maintainers = [{ name = "yu9824" }]
description = ""
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
keywords = []
# https://pypi.org/classifiers/
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
] # https://pypi.org/classifiers/

[project.optional-dependencies]
test = ["pytest"]
dev = ["build"]
optional = ["colorlog", "tqdm"]
docs = [
    "sphinx",
    "myst-parser",
    "myst-nb",
    "sphinx-book-theme",
    "jupyter-sphinx",
]
# gui = ["TkEasyGUI"]

[project.urls]
Homepage = "https://github.com/yu9824/lammps-utils"
Documentation = "https://yu9824.github.io/lammps-utils/"
# PyPI = "https://pypi.org/project/lammps-utils/"
Source = "https://github.com/yu9824/lammps-utils"
Tracker = "https://github.com/yu9824/lammps-utils/issues"
"Release Notes" = "https://github.com/yu9824/lammps-utils/releases"
# Changelog = "https://github.com/yu9824/lammps-utils/blob/main/CHANGELOG.md"

# [project.scripts]
# lammps-utils = "lammps_utils.__main__:entrypoint"

# [project.gui-scripts]
# lammps-utils-gui = "lammps_utils:main_gui"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.dynamic]
version = { attr = "lammps_utils.__version__" }

[tool.setuptools.packages.find]
where = ["src/"]

[tool.ruff]
line-length = 79
indent-width = 4

[tool.ruff.lint]
unfixable = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
